export const products = [
   {
    id: 1,
    brand: "Matisse",
    title: "Castrados Salmon",
    price: 190.00,
    stock: 8,
    weight: 7,
    description: "Formulado para auxiliar en el control del peso y mantener la masa muscular",
    category: "alimento-humedo",
    type: "Alimentos para gato adulto",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679109079/matissegatosadultoscastradossalmo-n8739_500x_xqh4ii.jpg",
    details:"Alimento completo para gatos adultos castrados.Libre de granos y libre de gluten. 100% proteína animal de pollo.",
    composition:"Composición:Carne de pollo deshidratada, tapioca, guisantes, proteína de pollo hidrolizada, levadura y extracto de levadura-Saccharomyces cerevisiae (Fuente de mananooligosacáridos – MOS y β-glucanos), grasa de ave (Fuente de ac. grasos Ω-6), hígado de pollo hidrolizado, proteína de patata, celulosa natural (Fuente de fibra insoluble), boniato, aceite de pescado (Fuente de ac. grasos Ω-3-EPA y DHA), pulpa de remolacha, vaina de algarroba, huevo entero deshidratado, minerales, Inulina (Fibra soluble de achicoria, fuente fosfooligosacáridos – FOS), fibra dietética soluble extraída de Plantago ovata, aceites esenciales (orégano, canela, clavo, tomillo, romero, hierba buena, té verde), yucca, hidrolizado de crustáceos (Fuente de Glucosamina), hidrolizado de cartílago (Fuente de Condroitina), concentrado de zumo de melón liofilizado (Rico en superoxido dismutasa – SOD)."
   },
   {
    id: 2,
    brand: "Bravery",
    title: "Chicken gatos",
    price: 199,
    stock: 80,
    weight: 7,
    description: "Receta de pollo de elevado contenido en proteínas, alta digestibilidad y palatabilidad.",
    category: "alimento-seco",
    type: "Alimentos para gato adulto",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679091278/BRAVERY_500x_pmmhgj.jpg"
   },
   {
    id: 3,
    brand: "N&D",
    title: "FELINE gatos adultos",
    price: 205,
    stock: 60,
    weight: 7,
    description: "Cuida el tratamiento urinario. Libre de OMG y sólo conservantes naturales.",
    category: "alimento-seco",
    type: "Alimentos para gato adulto",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679091510/ND-FRANGO_500x_xduf8o.jpg"
   },
   {
    id: 4,
    brand: "HILLS",
    title: "Contol bolas de pelo",
    price: 100,
    stock: 80,
    weight: 1.6,
    description: "Elaborado con una mezcla de fibras naturales que permiten deshacerse de las bolas de pelo",
    category: "alimento-seco",
    type: "Alimentos para gato adulto",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679092021/6-Hill_s_ScienceDiet_FelineAdultHairballControl_500x_xjhudh.jpg"
   },
   {
    id: 5,
    brand: "KLINKAT",
    title: "Arena de gato",
    price: 85,
    stock: 80,
    weight: 20,
    description: "Es un producto natural hecho de BENTONITA de alta calidad sin aditivos químicos.",
    category: "salud-bienestar",
    type: "Alimentos para gato adulto",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679092330/klinkat-arena-para-gatos_500x_way4qg.jpg"
   },
   {
    id: 6,
    brand: "KLINKAT",
    title: "Arena de gato",
    price: 85,
    stock: 80,
    weight: 7,
    description: "Es un producto natural hecho de BENTONITA de alta calidad sin aditivos químicos.",
    category: "salud-bienestar",
    type: "benzonita",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679092330/klinkat-arena-para-gatos_500x_way4qg.jpg"
   },
   {
    id: 7,
    brand: "AHARTZ",
    title: "Antipulgas P.I. gatos",
    price: 19,
    stock: 80,
    weight: 0.45,
    description: "INSECTICIDA - PULGUICIDA - PIOJICIDA  Dosis: 1 pipeta por animal, según peso. ",
    category: "salud-bienestar",
    type: "venta libre",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679109408/Pigato4-9_500x_se6wg3.jpg"
   },
   {
    id: 8,
    brand: "AHARTZ",
    title: "Shampoo x 440ml.",
    price: 30,
    stock: 80,
    weight: 440,
    description: "Reduce las bolas de pelo al eliminar el exceso de cabello suelto.",
    category: "salud-bienestar",
    type: "venta libre",
    delivery: 9.90,
    img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679093108/SHAMPOOPARAGATOSHARTZ_500x_grsif0.jpg"
   },
   {
      id: 2,
      brand: "Bravery",
      title: "Chicken gatos",
      price: 199,
      stock: 80,
      weight: 7,
      description: "Receta de pollo de elevado contenido en proteínas, alta digestibilidad y palatabilidad.",
      category: "alimento-seco",
      type: "Alimentos para gato adulto",
      delivery: 9.90,
      img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679091278/BRAVERY_500x_pmmhgj.jpg"
     },
     {
      id: 2,
      brand: "Bravery",
      title: "Chicken gatos",
      price: 199,
      stock: 80,
      weight: 7,
      description: "Receta de pollo de elevado contenido en proteínas, alta digestibilidad y palatabilidad.",
      category: "alimento-seco",
    type: "Alimentos para gato adulto",
      delivery: 9.90,
      img: "https://res.cloudinary.com/dzjf00pvx/image/upload/v1679091278/BRAVERY_500x_pmmhgj.jpg"
     },
]

